# -*- coding: utf-8 -*-
"""ALARM-CLOCK

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jDfJLLIsrqwEEs7R-vUOJvpyPluCO-F1
"""

import time
from datetime import datetime
!pip install playsound
from playsound import playsound

def set_alarm():
    alarm_date = input("Enter the date to set the alarm (YYYY-MM-DD): ")
    alarm_time = input("Enter the time to set the alarm (HH:MM:SS): ")
    time_format = input("Is this in 12-hour format? (yes/no): ").strip().lower()

    if time_format == "yes":
        period = input("Is it AM or PM? ").strip().upper()
        alarm_hour, alarm_minute, alarm_second = map(int, alarm_time.split(":"))
        if period == "PM" and alarm_hour != 12:
            alarm_hour += 12
        elif period == "AM" and alarm_hour == 12:
            alarm_hour = 0
    else:
        alarm_hour, alarm_minute, alarm_second = map(int, alarm_time.split(":"))

    alarm_datetime = datetime.strptime(f"{alarm_date} {alarm_hour}:{alarm_minute}:{alarm_second}", "%Y-%m-%d %H:%M:%S")
    alarm_set = True

    print(f"Alarm is set for {alarm_datetime}")

    while alarm_set:
        now = datetime.now()

        if now >= alarm_datetime:
            print("Wake up! It's time!")
            playsound('alarm_sound.mp3')  # Ensure you have an 'alarm_sound.mp3' file in the same directory
            alarm_set = False

        time.sleep(1)

if __name__ == "__main__":
    set_alarm()