# -*- coding: utf-8 -*-
"""PASSWORD-GENERATOR

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UGkoxw_clHFFUM_MgvZ6iR1KhPo2I0em
"""

import random
import string

def generate_password(length=8, use_upper=True, use_lower=True, use_digits=True, use_punctuation=True):
    character_set = ''
    if use_upper:
        character_set += string.ascii_uppercase
    if use_lower:
        character_set += string.ascii_lowercase
    if use_digits:
        character_set += string.digits
    if use_punctuation:
        character_set += string.punctuation

    if not character_set:
        raise ValueError("No character types selected. At least one type must be selected.")

    password = ''.join(random.choice(character_set) for i in range(length))
    return password

def main():
    print("Welcome to the Advanced Password Generator")
    try:
        length = int(input("Enter the desired length of the password: "))
        if length < 1:
            print("Length should be at least 1")
            return

        use_upper = input("Include uppercase letters? (yes/no): ").lower() == 'yes'
        use_lower = input("Include lowercase letters? (yes/no): ").lower() == 'yes'
        use_digits = input("Include digits? (yes/no): ").lower() == 'yes'
        use_punctuation = input("Include special characters? (yes/no): ").lower() == 'yes'

        password = generate_password(length, use_upper, use_lower, use_digits, use_punctuation)
        print(f"Generated Password: {password}")
    except ValueError as e:
        print(e)

if __name__ == "__main__":
    main()