# -*- coding: utf-8 -*-
"""Multiplayer_number_guessing_game

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w5HD3C0wPx9AcCbt7EF1vGjezedRzs6E
"""

import random

def get_difficulty_level():
    while True:
        print("Select Difficulty Level:")
        print("1. Easy (10 attempts per player)")
        print("2. Medium (7 attempts per player)")
        print("3. Hard (5 attempts per player)")

        choice = input("Enter the number of your choice: ")
        if choice == '1':
            return 10
        elif choice == '2':
            return 7
        elif choice == '3':
            return 5
        else:
            print("Invalid choice, please select again.")

def number_guessing_game():
    # Generate a random number between 1 and 100
    number_to_guess = random.randint(1, 100)
    max_attempts = get_difficulty_level()

    attempts = { "Player 1": 0, "Player 2": 0 }
    max_total_attempts = max_attempts * 2

    print("Welcome to the Multiplayer Number Guessing Game!")
    print(f"I have selected a number between 1 and 100. Each player has {max_attempts} attempts to guess it.")

    current_player = "Player 1"

    while sum(attempts.values()) < max_total_attempts:
        print(f"{current_player}, it's your turn!")

        # Get the player's guess
        try:
            guess = int(input(f"{current_player}, enter your guess: "))
        except ValueError:
            print("Please enter a valid number.")
            continue

        attempts[current_player] += 1

        # Compare the guess to the number and provide feedback
        if guess < number_to_guess:
            print("Too low!")
        elif guess > number_to_guess:
            print("Too high!")
        else:
            print(f"Congratulations {current_player}! You've guessed the number in {attempts[current_player]} attempts.")
            break

        # Switch to the other player
        current_player = "Player 2" if current_player == "Player 1" else "Player 1"
    else:
        print(f"Sorry, neither player guessed the number. The number was {number_to_guess}.")

if __name__ == "__main__":
    number_guessing_game()
